# Tour Formation Configuration

# Global Parameters
global:
  wh_id: 'AVP1'                              # Warehouse ID 
  avg_pick_uph: 50                           # Average pick units per hour
  container_target_variability_factor: 1.2   # Variability factor
  tf_min_containers_in_backlog: 1000         # Minimum number of containers in backlog to trigger TF

# Slack Calculation Parameters (change by FC)
slack_calculation:
  buffer_variability_factor: 1.25       
  other_time_buffer: 60              # minutes for grooming, packing, shipping
  travel_time_constant: 5            # minutes per aisle
  aisle_crossing_factor: 20          # factor for crossing aisles vs traveling in aisles
  critical_slack_threshold: 0
  urgent_slack_threshold: 60
  avg_cycle_time: 150                # Average cycle time in minutes
  avg_time_to_prepare_tour: 5        # Average time to prepare a tour in minutes
  weights:
    critical: 10.0
    urgent: 5.0
    safe: 0.0
  
  # Time-of-day capacity dictionary (0=no capacity, 1=full capacity)
  capacity_by_hour: {
    0: 1.0, 1: 1.0, 2: 1.0, 3: 1.0, 4: 1.0, 5: 0.0,   # Nightshift (10:00 PM - 1:30 AM, 2:00 AM - 5:00 AM)
    6: 0.0, 7: 0.5, 8: 1.0, 9: 1.0, 10: 0.5,          # Dayshift (7:30 AM - 10:30 AM)
    11: 1.0, 12: 1.0, 13: 1.0, 14: 1.0, 15: 0.5,      # Dayshift (11:00 AM - 3:00 PM)
    16: 1.0, 17: 1.0, 18: 0.5,                        # Dayshift (3:30 PM - 6:00 PM)
    19: 1.0, 20: 1.0, 21: 1.0, 22: 0.5, 23: 1.0       # Nightshift (6:30 PM - 9:30 PM, 10:00 PM - 1:30 AM)
  }

# Clustering Parameters
# Feature Engineering Parameters
feature_engineering:
  weights:
    centroid: 0.7                 # Weight for aisle centroid feature
    span: 0.3                      # Weight for aisle span feature
    distinct_aisles: 0.0           # Weight for distinct aisles feature
  use_distinct_aisles: false        # Whether to use distinct aisles as a feature

clustering:
  max_cluster_size: 200              # Maximum cluster size / Max MIP Problem Size
  min_clusters: 2                  # Minimum number of clusters to form
  max_clusters: 10                 # Maximum number of clusters to form
  linkage_method: 'ward'           # Hierarchical clustering linkage method (ward, complete, average, single)
  generate_visualizations: false      # Enable/disable visualization of clusters
  max_residual_attempts: 5           # Maximum number of attempts to assign residual containers
  subclustering:
    max_depth: 6                   # Maximum recursion depth for subclustering

# Tour Formation Parameters
tour_formation:
  tf_interval: 30                    # Interval of tour formation in minutes
  min_containers_per_tour: 20        # Cmin: min. number of containers per tour
  max_containers_per_tour: 20        # Cmax: max. number of containers per tour
  early_termination_seconds: 60      # Early termination time in seconds
  travel_distance_weight: 20.0        # Weight for travel distance in objective function
 

  solver:
    early_termination_seconds: 60
    output_flag: 0                   # Output flag for solver
    mip_gap: 0.05                    # MIP gap tolerance
    time_limit: 1200                 # Time limit in seconds

# Gurobi Settings
gurobi:
  LOG_FILE: 'logs/gurobi.log'
  ISV_NAME: 'Chewy'
  APP_NAME: 'DS'
  EXPIRATION: 20260331
  CODE: 'XG5VKFHH'

# Logging Configuration
logging:
  log_base_dir: 'logs'
  console_level: 'INFO'
  file_level: 'INFO'
  console_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file_format: '%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s'