#Sim. Configuration
global:
  wh_id: 'AVP1'
  input_mode: 1                     # 1 - load from Vertica, #2 - use CSV input files
  start_time: '2025-01-22 15:00:00'
  end_time: '2025-01-22 15:29:00' 
  hourly_container_target: 1000

#Optimization Parameters
tour_formation:

  tf_interval: 30                 # Interval of tour formation in minutes
  min_containers_per_tour: 20      # Cmin: min. number of containers per tour
  max_containers_per_tour: 20      # Cmax: max. number of containers per tour
  clustering_enabled: true         # Enable clustering to decompose the problemn
  max_cluster_size: 200            # Maximum cluster size
  max_residual_attempts: 5         # Maximum number of attempts to assign residual containers
  early_termination_seconds: 120   # Early termination time in seconds, if the incumbent solution does not improve

  weights:
    lateness: 5                   # alpha: Weight for lateness (this will be replaced by slack weights)
    distinct_aisles: 20           # beta: Weight for distinct aisles
    #distance: 1                   # beta: Weight for travel distance
    tour_count: 1000              # gamma: Weight for minimizing number of tours
    
  solver:
    output_flag: 1                  # Output flag for solver
    mip_gap: 0.05                   # MIP gap tolerance
    time_limit: 1200                # Time limit in seconds

tour_allocation:

  max_pickers: 2                   # Number of available pickers
  ta_interval: 30                     # Interval of tour formation in minutes
  avg_cycle_time: 10               # Average cycle time in minutes
  avg_time_to_prepare_tour: 2       # Average time to prepare a tour in minutes
  buffer_variability_factor: 1.25   # Buffer variability factor

  weights:
    concurrency: 1.0               # Weight for aisle concurrency
    lateness: 5.0                  # Weight for lateness in allocation

  solver:
    output_flag: 0                 # Output flag for solver
    mip_gap: 0.01                  # MIP gap tolerance
    time_limit: 300                # Time limit in seconds


# Logging Configuration
logging:

  console_level: INFO
  file_level: INFO
  main_log_file: '../logs/pickplanning-sim.log'
  workflow_log_dir: '../logs/workflows'
  enable_workflow_logs: False
  log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'


#Database Configuration
database:

  vertica:
    host: 'bidb.chewy.local'
    port: 5433
    database: 'bidb'
    credentials_file: 'C:/Users/{username}/cred.txt'  # Path to the encrypted credentials file - enter username

  mssql:
    server: 'datahubsql-ro.chewy.local'
    as_dict: true
